# Config file for automatic testing at travis-ci.org

sudo: false
language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27

install:
  - pip install -r requirements.txt

script: tox 

after_failure:
  - cat /home/travis/build/alexandriagroup/fnapy/.tox/log/tox-0.log
